version: '3'

services:
  backend:
    container_name: "kupipodaridai-backend"
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-compose-kupipodaridai
    restart: always
    ports:
      - '4000:3000'
    env_file: ./backend/.env
    networks:
      - internal

  frontend:
    container_name: 'kupipodaridai-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-compose-kupipodaridai
    restart: always
    ports:
      - '8080:80'
    networks:
      - external  

  postgres:
    container_name: 'postgres'
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal

  adminer:
    container_name: 'adminer'
    image: adminer
    restart: always
    ports:
      - '8081:8080'  # Adminer будет доступен на порту 8081 на хосте
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
  external:
